[build]
  command = "npm run build"
  publish = ".next"  # let the plugin handle serverless deployment
  environment = { NEXT_TELEMETRY_DISABLED = "1" }

[[plugins]]
  package = "@netlify/plugin-nextjs"
